name: Sync

on:
  push:
    branches: [main, hugo]

jobs:
  sync-2-gitee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync to Gitee
        uses: ./.github/actions/git-mirror-action
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:zh79325/jxh-ai-server.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:jingxiaohe123/jxh-ai-server.git
